parameters:
  wordpress.acf_path: "%template_dir%/app/config/acf"
  wordpress.acf_menu: "%wp_debug%"
  wordpress.theme_support:
    - "html5"
    - "post-thumbnails"
  wordpress.translations: "%template_dir%/languages"
  wordpress.image_sizes:
    fullscreen: [1920, 1080, true]
    teaser: [800, 500, true]
  wordpress.menus:
    primary_menu: "Primary Menu"
    footer_menu: "Footer Menu"
  wordpress.sidebars:
    - { id: "sample_sidebar", name: "sample sidebar", description: "sample sidebar managed by config file" }
  wordpress.inline_styles:
    - { id: "inline", source: "%template_dir%/web/stylesheets/inline.css" }
  wordpress.styles:
    - { id: "fonts", source: "https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,400i,700,700i", deps: ~ }
    - { id: "app", source: "%template_uri%/web/stylesheets/app.css", deps: ['fonts'] }
  wordpress.inline_scripts:
    - { id: "inline", source: "%template_dir%/web/scripts-min/inline.min.js" }
  wordpress.scripts:
    - { id: "flowplayer", source: "%template_uri%/web/flowplayer/flowplayer-3.2.13.min.js", deps: ['jquery'], header: false }
    - { id: "app", source: "%template_uri%/web/scripts-min/app-debug.js", deps: ['jquery'], header: false }
  wordpress.post_types:
    success_stories:
      public: true
      has_archive: true
      labels: {name: "Success Stories", singular_name: "Success Story"}
      menu_position: 6
      menu_icon: "dashicons-portfolio"
      supports: ["title", "editor", "thumbnail"]
    videos:
      public: true
      show_in_rest: false
      has_archive: true
      labels: {name: "Videos", singular_name: "Video"}
      menu_position: 6
      menu_icon: "dashicons-video-alt3"
      supports: ["title", "editor", "thumbnail"]
      capabilities:
        edit_post: "edit_videos"
        edit_posts: "edit_videos"
        edit_others_posts: "edit_other_videos"
        publish_posts: "publish_videos"
        read_post: "read_video"
        read_private_posts: "read_private_videos"
        delete_post: "delete_video"